services:
  bind9:
    image: internetsystemsconsortium/bind9:9.20
    container_name: bind9
    user: "1000:1000"
    restart: unless-stopped
    network_mode: host
    command: -u 1000 -c /etc/bind/named.conf -g
    volumes:
      - ./named.conf:/etc/bind/named.conf:ro
      - ./zones:/zones
