options {
    directory "/var/cache/bind";

    listen-on port 53 { any; };
    listen-on-v6 { any; };

    recursion yes;
    allow-query { any; };
    allow-recursion { any; };

    forwarders {
        10.130.5.1;
    };
    forward only;

    dnssec-validation no;
};

key "externaldns-key" {
    algorithm hmac-sha256;
    secret "${RFC2136_TSIG_SECRET}";
};

zone "internal" IN {
    type primary;
    file "/zones/db.internal";
    allow-update { key "externaldns-key"; };
};

zone "home" IN {
    type forward;
    forward only;
    forwarders { 10.130.5.1; };
};
